### ISSUE TITLE
Make Values label optional

### ISSUE THREAD

**Issue by nshea3** [nekoumei/dtreeplt#7]
Love this project so far! Thank you! 

Currently working with a multiclass classification problem. I have 9 different classes and the class counts overflow and look messy. 

![image](https://user-images.githubusercontent.com/25097799/60689265-528cdd80-9e70-11e9-8e74-7bbbcb783bdd.png)

Made changes to make the Values label optional, added attribute disp_values to dtreeplt class, this alters the text concatenation in the  _get_texts method to substitute in a blank string if disp_values is False. 

Will send a pull request shortly.

**Comment by BhekiMabheka** [comment]
@nekoumei  in your package dtreeplt, how do you visualize the yes and no part from the node?

**Comment by nekoumei** [comment]
> @nekoumei in your package dtreeplt, how do you visualize the yes and no part from the node?

Sorry. This cannot make it visible.
Nodes are always True on the left and False on the right. (Same as export_graphviz)
